server:
  port: 8080
  

spring:
  application:
    name: spring-retry-demo
  datasource:
    #url: jdbc:sqlserver://localhost;databaseName=master;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: Mystrongpass123
    #driverClassName: com.mysql.cj.jdbc.Driver
    #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
             org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
             org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    
  jpa:
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.SQLServerDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true